### ISSUE TITLE
Error in Deadliner: Deadline Countdown for Exams add-on

### ISSUE THREAD

**Issue by Adanze168** [nairboon/deadliner#1]
I couldn't see the deadlines I created on decks (PC) and then I got this error message:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.66 (70506aeb) Python 3.9.15 Qt 6.5.2 PyQt 6.5.2
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-10-19 14:14:04
Add-ons possibly involved: ⁨Deadliner Deadline Countdown for Exams⁩

Caught exception:
Traceback (most recent call last):
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 190, in closeEvent
    refreshDeadliner()
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 36, in refreshDeadliner
    dm.refresh()
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 68, in refresh
    self._deadlines = findDeadlines()
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 373, in findDeadlines
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 373, in <listcomp>
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 254, in __init__
    avg_reps, avg_sec = self.get_train_stats(deck_id)
  File "C:\Users\paula\AppData\Roaming\Anki2\addons21\1560797112\__init__.py", line 348, in get_train_stats
    childDeck[1] for childDeck in mw.col.decks.children(self.deck_id)
  File "anki.decks", line 468, in children
  File "anki.decks", line 461, in deck_and_child_name_ids
  File "anki._backend_generated", line 370, in get_deck_and_child_names
  File "anki._backend", line 151, in _run_command
anki.errors.NotFoundError: Your database appears to be in an inconsistent state. Please use the Check Database action.

**Comment by nairboon** [comment]
please try to update the Addon to the latest version and check if this fixes your error
