### ISSUE TITLE
New Bug Error Message 

### ISSUE THREAD

**Issue by laurens15** [nairboon/deadliner#3]
Hello, 

Today I went to refresh my deadliner add on and it began showing error messages. 

I have toggled on and off the add on, deleted and redownloaded, but nothing seems to make it work again. I have attached the pop up I am repeatedly receiving. 

Any troubleshooting help would be great, as this is my favorite add on!

Thank you!

<img width="499" alt="Screenshot 2023-12-09 at 10 32 42 PM" src="https://github.com/nairboon/deadliner/assets/153408972/d3e30a46-693a-4a6d-87d7-474cd1ee438c">

**Comment by nairboon** [comment]
Could you paste the whole error message by clicking the "Copy to Clipboard" button?

**Comment by laurens15** [comment]
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "aqt.main", line 1068, in maybe_auto_sync_on_open_close
  File "aqt.main", line 1063, in _sync_collection_and_media
  File "aqt.sync", line 128, in sync_collection
  File "aqt.taskman", line 108, in with_progress
  File "aqt.taskman", line 69, in run_in_background
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 379, in display_footer
    deadlines = dm.deadlines
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 64, in deadlines
    self.refresh()
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 68, in refresh
    self._deadlines = findDeadlines()
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 373, in findDeadlines
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 373, in <listcomp>
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 254, in __init__
    avg_reps, avg_sec = self.get_train_stats(deck_id)
  File "/Users/laurensadik/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 348, in get_train_stats
    childDeck[1] for childDeck in mw.col.decks.children(self.deck_id)
  File "anki.decks", line 467, in children
  File "anki.decks", line 460, in deck_and_child_name_ids
  File "anki._backend_generated", line 455, in get_deck_and_child_names
  File "anki._backend", line 166, in _run_command
anki.errors.NotFoundError: Your database appears to be in an inconsistent state. Please use the Check Database action.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Deadliner Deadline Countdown for Exams ['1560797112', 2023-04-06T05:57, 'None', '']
Review Heatmap ['1771074083', 2022-06-29T21:43, 'None', '']
The KING of Button Add-ons ['374005964', 2024-01-03T16:07, 'None', '']
link Cards Notes and Preview them in extra window ['1423933177', 2023-10-27T18:26, 'None', '']

===IDs of active AnkiWeb add-ons===
1423933177 1560797112 1771074083 374005964

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by nairboon** [comment]
please try to update the Addon to the latest version and check if this fixes your error
