### ISSUE TITLE
to update a stack

### ISSUE THREAD

**Issue by frank260119** [nairboon/deadliner#4]
Hello, 
my issue is that I had to update a stack with an deadline and now every time I start Anki that plops up:
<img width="262" alt="Bildschirmfoto 2024-01-13 um 11 30 54" src="https://github.com/nairboon/deadliner/assets/131150145/e4cb595b-b7a4-424f-95af-787579be451a">
and thats the issue:
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: macOS-14.2.1-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 218, in on_window_init
  File "aqt.main", line 317, in setupProfile
  File "aqt.main", line 530, in loadProfile
  File "aqt.main", line 1068, in maybe_auto_sync_on_open_close
  File "aqt.main", line 1063, in _sync_collection_and_media
  File "aqt.sync", line 128, in sync_collection
  File "aqt.taskman", line 108, in with_progress
  File "aqt.taskman", line 69, in run_in_background
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.operations", line 260, in wrapped_done
  File "aqt.deckbrowser", line 170, in success
  File "aqt.deckbrowser", line 186, in __renderPage
  File "_aqt.hooks", line 1837, in __call__
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 379, in display_footer
    deadlines = dm.deadlines
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 64, in deadlines
    self.refresh()
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 68, in refresh
    self._deadlines = findDeadlines()
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 373, in findDeadlines
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 373, in <listcomp>
    return [DeadlineStats(int(k), v["name"], v["deadline"]) for k,v in db.deadlines.items() if v['enabled']]
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 254, in __init__
    avg_reps, avg_sec = self.get_train_stats(deck_id)
  File "/Users/florian/Library/Application Support/Anki2/addons21/1560797112/__init__.py", line 348, in get_train_stats
    childDeck[1] for childDeck in mw.col.decks.children(self.deck_id)
  File "anki.decks", line 467, in children
  File "anki.decks", line 460, in deck_and_child_name_ids
  File "anki._backend_generated", line 455, in get_deck_and_child_names
  File "anki._backend", line 166, in _run_command
anki.errors.NotFoundError: Ihre Datenbank scheint sich in einem inkonsistenten Zustand zu befinden. Bitte benutzen Sie die Aktion Datenbank überprüfen.

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Deadliner Deadline Countdown for Exams ['1560797112', 2023-04-06T11:57, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T03:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1560797112 1771074083

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])

can you help me?

**Comment by nairboon** [comment]
please try to update the Addon to the latest version and check if this fixes your error
